# JDBC Authentication Database Schema
# This script creates the default Spring Security JDBC schema for H2 database

# Users table - stores user accounts
CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL PRIMARY KEY,
    password VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL
);

# Authorities table - stores user roles/authorities  
CREATE TABLE IF NOT EXISTS authorities (
    username VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY(username) REFERENCES users(username)
);

# Unique index on username,authority to prevent duplicate role assignments
CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_username ON authorities (username, authority);

# Groups table (optional) - for group-based permissions
CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    group_name VARCHAR(50) NOT NULL
);

# Group members table - assigns users to groups
CREATE TABLE IF NOT EXISTS group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT fk_group_members_group FOREIGN KEY(group_id) REFERENCES groups(id)
);

# Group authorities table - assigns authorities to groups
CREATE TABLE IF NOT EXISTS group_authorities (
    group_id BIGINT NOT NULL,
    authority VARCHAR(50) NOT NULL,
    CONSTRAINT fk_group_authorities_group FOREIGN KEY(group_id) REFERENCES groups(id)
);