dependencies {
    api project(':common-auth')
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'io.grpc:grpc-stub'
    implementation 'io.grpc:grpc-netty-shaded'
}
